# Generated by Django 5.1.5 on 2026-07-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.URLField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('blocked', 'Blocked'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'API Statuses',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('year_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pe_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('pb_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('dividend_yield', models.CharField(blank=True, max_length=20, null=True)),
                ('advances', models.IntegerField(blank=True, null=True)),
                ('declines', models.IntegerField(blank=True, null=True)),
                ('unchanged', models.IntegerField(blank=True, null=True)),
                ('change_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('change_365d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndexHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.index')),
            ],
            options={
                'verbose_name_plural': 'Index Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
